version: '3.8'

services:
  okx-api-client:
    build: .
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - RUST_LOG=info
    command: ["--help"]
    
  okx-api-client-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    working_dir: /app
    environment:
      - RUST_LOG=info
    command: ["cargo", "run", "--", "positions", "--simple"]

volumes:
  cargo-cache:
  target-cache: 